//
// AlertType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum AlertType: String, Codable {
    case unknown = "UNKNOWN"
    case air = "AIR"
    case artillery = "ARTILLERY"
    case urbanFights = "URBAN_FIGHTS"
    case chemical = "CHEMICAL"
    case nuclear = "NUCLEAR"
    case info = "INFO"
}