//
// AlertModification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AlertModification: Codable {

    public var lastActionIndex: Int64?

    public init(lastActionIndex: Int64? = nil) {
        self.lastActionIndex = lastActionIndex
    }


}
