//
// Alert.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Alert: Codable {

    public var regionId: String?
    public var regionType: V2RegionType?
    public var type: AlertType?
    public var lastUpdate: Date?

    public init(regionId: String? = nil, regionType: V2RegionType? = nil, type: AlertType? = nil, lastUpdate: Date? = nil) {
        self.regionId = regionId
        self.regionType = regionType
        self.type = type
        self.lastUpdate = lastUpdate
    }


}
