//
// AlertRegionModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AlertRegionModel: Codable {

    public var regionId: String?
    public var regionType: V2RegionType?
    public var regionName: String?
    public var regionEngName: String?
    public var lastUpdate: Date?
    public var activeAlerts: [Alert]?

    public init(regionId: String? = nil, regionType: V2RegionType? = nil, regionName: String? = nil, regionEngName: String? = nil, lastUpdate: Date? = nil, activeAlerts: [Alert]? = nil) {
        self.regionId = regionId
        self.regionType = regionType
        self.regionName = regionName
        self.regionEngName = regionEngName
        self.lastUpdate = lastUpdate
        self.activeAlerts = activeAlerts
    }


}
