//
// RegionsViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegionsViewModel: Codable {

    public var states: [RegionViewModel]?

    public init(states: [RegionViewModel]? = nil) {
        self.states = states
    }


}
