//
// RegionViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegionViewModel: Codable {

    public var regionId: String?
    public var regionName: String?
    public var regionType: V2RegionType?
    public var regionChildIds: [RegionViewModel]?

    public init(regionId: String? = nil, regionName: String? = nil, regionType: V2RegionType? = nil, regionChildIds: [RegionViewModel]? = nil) {
        self.regionId = regionId
        self.regionName = regionName
        self.regionType = regionType
        self.regionChildIds = regionChildIds
    }


}
