//
// RegionAlarmsHistory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegionAlarmsHistory: Codable {

    public var regionId: String?
    public var regionName: String?
    public var alarms: [RegionAlarmModel]?

    public init(regionId: String? = nil, regionName: String? = nil, alarms: [RegionAlarmModel]? = nil) {
        self.regionId = regionId
        self.regionName = regionName
        self.alarms = alarms
    }


}
