//
// RegionAlarmModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegionAlarmModel: Codable {

    public var regionId: String?
    public var startDate: Date?
    public var endDate: Date?
    public var duration: TimeSpan?
    public var alertType: AlertType?
    public var regionName: String?
    public var isContinue: Bool?

    public init(regionId: String? = nil, startDate: Date? = nil, endDate: Date? = nil, duration: TimeSpan? = nil, alertType: AlertType? = nil, regionName: String? = nil, isContinue: Bool? = nil) {
        self.regionId = regionId
        self.startDate = startDate
        self.endDate = endDate
        self.duration = duration
        self.alertType = alertType
        self.regionName = regionName
        self.isContinue = isContinue
    }


}
