//
// V2RegionType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum V2RegionType: String, Codable {
    case state = "State"
    case district = "District"
    case community = "Community"
    case null = "Null"
}