//
// WebHookModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WebHookModel: Codable {

    public var webHookUrl: String?

    public init(webHookUrl: String? = nil) {
        self.webHookUrl = webHookUrl
    }


}
